### ISSUE TITLE
`gradle build` fails

### ISSUE THREAD

**Issue by pselvana** [forcedotcom/JavaChatterRESTApi#11]
Looks like with the missing clover.license file, the `gradle build` will fail.
Maybe update the readme.md to add where to get a valid license?

Download https://repo1.maven.org/maven2/com/atlassian/clover/clover/4.1.1/clover-4.1.1.jar
[clover-clean] Clover Version 4.1.1, built on December 07 2015 (build-977)
[clover-clean] Loaded from: /root/.gradle/caches/modules-2/files-2.1/com.atlassian.clover/clover/4.1.1/26f74a1fcaf03d231be3ed89df0b28d6e0df8d84/clover-4.1.1.jar
[clover-clean] No license file found.
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> java.lang.RuntimeException: Invalid or missing License.. Please visit http://my.atlassian.com to obtain a valid license.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 41.485 secs
[debug] Running post-Build Cache steps
[info] build failed (exit code 1)

**Comment by jasperroel** [comment]
@pselvana acknowledged and thanks for the heads up.

I've created a PR that should hopefully resolves this for those without Clover.

**Comment by pselvana** [comment]
@jasperroel Thanks!
You may want to setup a free build at drone.io or travis-ci.org since this is a public project.
Here's a sample `.drone.yml` file if you wanted to use drone.io that worked for me:
8<----------
build:
  image: qlik/gradle
  commands:
    - gradle assemble
    - gradle build
------->8

I think you can also add markup for latest status in the READM.md markup.

**Comment by jasperroel** [comment]
Thanks for the suggestion. I recently got an Open Source license for the Atlassian cloud setup (Jira, Bamboo, Clover) where I am hosting the tests/integrations:

https://jasperroel.atlassian.net/builds/browse/JCRA-JCRA

This also has the clover integration that broke your build:
https://jasperroel.atlassian.net/builds/browse/JCRA-JCRA/latest/artifact/JOB1/Clover-Report-%28System%29/dashboard.html

Bamboo cloud doesn't seem to have the fancy badge integration that travisCI offers, except through custom tasks or coding (suggested here http://broonix-rants.ghost.io/updating-github-status-from-bamboo/).

The Atlassian integration is quite recent, but the integration of things like code coverage (for this and another open source project I have) are quite appealing. I'll at least work on mentioning the Atlassion project in the README.
